### ISSUE TITLE
Dead Readme link in header on Hackage 

### ISSUE THREAD

**Issue by wallymathieu** [agentultra/postgresql-replicant#11]
The link https://hackage.haskell.org/package/postgresql-replicant
goes to
https://github.com/agentultra/postgres-replicant#readme
instead of the expected
https://github.com/agentultra/postgresql-replicant#readme

**Comment by agentultra** [comment]
Thank you for the report!

**Comment by agentultra** [comment]
Fixed! In 19e7553
