### ISSUE TITLE
LSN instances can be written shorter

### ISSUE THREAD

**Issue by Vlix** [agentultra/postgresql-replicant#7]
Maybe a bit pedantic, but saw it so I thought I'd add it nonetheless. 🤷 

```haskell
instance Ord LSN where
  compare (LSN l0 r0) (LSN l1 r1) =
    compare l0 l1 <> compare r0 r1

instance Serialize LSN where
  put = putInt64be . toInt64
  get = fromInt64 <$> getInt64be
```

Do like the idea of this library. Will be checking out more when I get the time. 👍

**Comment by agentultra** [comment]
Thanks for the issue! I'll look into this. 👍

**Comment by agentultra** [comment]
Thanks @Vlix updated in https://github.com/agentultra/postgresql-replicant/commit/4eeb96355b629f5c1070d15c4e5090bf37389c5c
